from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from wiki_store import WikiItem, append_wiki_items, wiki_hash


def load_items(path: str | Path) -> list[WikiItem]:
    value = json.loads(Path(path).read_text(encoding="utf-8"))
    raw_items = value.get("items") if isinstance(value, dict) else value
    if not isinstance(raw_items, list):
        raise ValueError("wiki item input must be an array or an object with an items array")
    items: list[WikiItem] = []
    for raw in raw_items:
        if not isinstance(raw, dict):
            continue
        item = item_from_agent(raw)
        if item.text:
            items.append(item)
    return items


def item_from_agent(raw: dict[str, Any]) -> WikiItem:
    kind = str(raw.get("kind") or "claim").strip()
    title = str(raw.get("title") or "").strip()
    summary = str(raw.get("summary") or raw.get("description") or title).strip()
    source_id = str(raw.get("sourceId") or raw.get("source_id") or "").strip()
    source_title = str(raw.get("sourceTitle") or raw.get("source_title") or "").strip()
    tags = raw.get("tags") if isinstance(raw.get("tags"), list) else []
    related = raw.get("related") if isinstance(raw.get("related"), list) else []
    digest = wiki_hash(kind, title, summary, source_id, source_title)
    return WikiItem(
        id=str(raw.get("id") or f"wiki:{digest[:16]}"),
        kind=kind,
        title=title,
        summary=summary,
        source_id=source_id,
        source_title=source_title,
        source_date=str(raw.get("sourceDate") or raw.get("source_date") or "").strip(),
        tags=[str(item).strip() for item in tags if str(item).strip()],
        related=[str(item).strip() for item in related if str(item).strip()],
        status=str(raw.get("status") or "accepted").strip() or "accepted",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Save accepted LLM WIKI items into the skill-owned memory store.")
    parser.add_argument("--input", required=True, help="JSON file containing wiki items generated by the calling agent.")
    parser.add_argument("--memory-home", help="Local memory store directory.")
    args = parser.parse_args()

    items = load_items(args.input)
    stats = append_wiki_items(items, args.memory_home)
    print(json.dumps({"wiki": stats}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
